### ISSUE TITLE
Building with protobuf from github yields warning

### ISSUE THREAD

**Issue by tsee** [mbarbon/google-protobuf-dynamic#2]
Just built with protobuf from github and get the following warnings:

[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: scalar.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)

Probably doesn't matter yet, but eventually will. :)

(Sorry for not just patching this.)

**Comment by mbarbon** [comment]
Should be fixed by 7bc63c8b9b1a2b75a749aecab4754bdc33fa57ee, let me know if I missed one.
