### ISSUE TITLE
undefined symbol during test

### ISSUE THREAD

**Issue by martinthurn** [mbarbon/google-protobuf-dynamic#23]
martin@L3-37:~/.cpanplus/5.22.1/build/liaRtZfsYD/Google-ProtocolBuffers-Dynamic-0.22$ ./Build test
t/001_load.t .................... 1/1 
   Failed test 'use Google::ProtocolBuffers::Dynamic;'
   at t/001_load.t line 8.
     Tried to use 'Google::ProtocolBuffers::Dynamic'.
     Error:  Can't load '/media/martin/91e9c4bd-9f2c-4734-a835-3af3ebd6fe41/cpanplus/5.22.1/build/liaRtZfsYD/Google-ProtocolBuffers-Dynamic-0.22/blib/arch/auto/Google/ProtocolBuffers/Dynamic/Dynamic.so' for module Google::ProtocolBuffers::Dynamic: /media/martin/91e9c4bd-9f2c-4734-a835-3af3ebd6fe41/cpanplus/5.22.1/build/liaRtZfsYD/Google-ProtocolBuffers-Dynamic-0.22/blib/arch/auto/Google/ProtocolBuffers/Dynamic/Dynamic.so: undefined symbol: _ZN6google8protobuf8internal21StringTypeHandlerBase3NewB5cxx11Ev at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 187.
  at t/001_load.t line 8.
 Compilation failed in require at t/001_load.t line 8.
 BEGIN failed--compilation aborted at t/001_load.t line 8.
 Looks like you failed 1 test of 1.
t/001_load.t .................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests

**Comment by mbarbon** [comment]
This usually happens when you have Alien::uPB compiled with one protobuf version, and then upgrade protobuf.

Removing and reinstalling Alien::uPB should fix this issue.

**Comment by martinthurn** [comment]
Yes thank you that seemed to fix it.
