### ISSUE TITLE
Wishlist: JSON in-/output

### ISSUE THREAD

**Issue by tsee** [mbarbon/google-protobuf-dynamic#3]
I believe upb supports JSON in- and output transparently while using the same protobuf schemas. I think as a not-protobuf-enabled-client compatibility layer, supporting this in GPB::Dynamic as something like encode_json/decode_json for the generated mapper classes would be awesome.

(And yeah, I have a work use case in mind for that.)

**Comment by mbarbon** [comment]
I planned to add this, but it's not my top priority

**Comment by tsee** [comment]
Just for context, I was wondering if this wasn't potentially very useful for some interop corner cases at work. Not urgent, though. Can share more in person if you like.

**Comment by mbarbon** [comment]
Implemented encode_json() and decode_json() in version 0.05
