### ISSUE TITLE
Mapper presumes upb const_field_iterator order

### ISSUE THREAD

**Issue by edam** [mbarbon/google-protobuf-dynamic#34]
The underlying `upb` library provides `const_field_iterator` which is used in `mapper.cpp` to iterate over `FieldDef`s and field information is stored in that order in a `fields` vector.

Later, `const_oneof_iterator` is used to iterate over the "oneof" fields, and `field_def->index()` is used to access the fields vector to delete any existing value for the "oneof".

The presumption here is that `field_def->index()` is usable to index the list of fields returned by `const_field_iterator` in the order they're returned.

This presumption turns out not to be correct. The question is, what is correct?

* Should upb's `const_field_iterator` return fields in `field_def->index()` order?

* Or is `field_def->index()` really unrelated to the order that `const_field_iterator` returns fields in, and `Mapper::Mapper()` should use `field_def->index()` to populate the vector of fields?

To recreate this issue:

tim.proto:
```proto
syntax = "proto3";

message A {

	int32 val = 1;

	oneof foo {
		B b = 2;
		C c = 3;
	}

	message B {
		int32 val = 1;
	}

	message C {
		int32 val = 1;
	}
}
```

tim.pl:
```perl
#!/usr/bin/perl
use strict;
use warnings;
use 5.008;
use Google::ProtocolBuffers::Dynamic;

my $dynamic = Google::ProtocolBuffers::Dynamic->new( '.' );
$dynamic->load_file( 'tim.proto' );
$dynamic->map( { message => 'A', to => 'A' } );

my $json = '{"val":5,"b":{"val":6}}';

my $data = A->decode_json( $json );

print "A.val = ".$data->get_val."\n";
```

output:
```bash
$ ./tim.pl
A.val = 0
```

epected output:
```bash
$ ./tim.pl
A.val = 5
```

This happens because, when decoding `"b":{"val":6}`, the `Field` definition for `b` has a `oneof_index` which causes the decoder to look for any existing value in that "oneof" group, which will need to be deleted.  Unfortunately, the initial `"val":5` field definition also says it's in the same "oneof" group, and so `A.val` is deleted.

The `oneof_index`es are set up incorrectly in `Mapper::Mapper()`, when iterating over the oneof groups.  The following code in `mapper.cpp` is where that happens:

```c++
        for (OneofDef::const_iterator it = oneof_def->begin(), en = oneof_def->end(); it != en; ++it) {
            const FieldDef *field_def = *it;
            Field &field = fields[field_def->index()]; // <-- CAN PICK WRONG FIELD
            field.oneof_index = oneof_index;
        }
```

What is the correct fix? A change in `mapper.cpp`? Or a change in upb?

**Comment by mbarbon** [comment]
This should be fixed in 0.25
