### ISSUE TITLE
Too late to run CHECK block at X.pm line 4294967295

### ISSUE THREAD

**Issue by vphantom** [mbarbon/google-protobuf-dynamic#40]
Hi! I'm reporting this here in case anyone else stumbles on this issue.

I notice that I have to `use X.pm` (generated by `protoc`) as early as possible in my program flow in order to avoid that warning, which I'm hoping is benign.

That said, with Apache/mod_perl I cannot get rid of that warning every time a new Apache child is forked.  I tried using the module in my `handler.pl`, and even in the Apache configuration itself in `PerlModule`, `PerlLoadModule`, `PerlRequire`, `PerlPostConfigRequire`.

The only places I found `CHECK` in `/usr/` were in `ExtUtils/XSpp/Grammar.pm` and this module's `Dynamic.so`.  I'm not too sure how to investigate this further. There doesn't seem to be a way to look at generated code since it's generated dynamically at module load time.

**Comment by mbarbon** [comment]
This looks like the same underlying issue as #46 (Perl treats some names in a special way).

My guess is that the `proto` file has an `enum` with a value named `CHECK`.
