### ISSUE TITLE
protoc-gen-perl-gpd don't working

### ISSUE THREAD

**Issue by Logioniz** [mbarbon/google-protobuf-dynamic#42]
Try to use protoc-gen-perl-gpd to generate module but the script never exits and prints warnings. 

```bash
root@5332d16ec3b9:/client# protoc-gen-perl-gpd --perl-gpd_out=package=Avatica.Client.Protocol:lib 1.proto
\1 better written as $1 at /usr/local/lib/perl5/site_perl/5.34.0/x86_64-linux-gnu/Google/ProtocolBuffers/Dynamic/MakeModule.pm line 57.
\2 better written as $2 at /usr/local/lib/perl5/site_perl/5.34.0/x86_64-linux-gnu/Google/ProtocolBuffers/Dynamic/MakeModule.pm line 57.
^C
root@5332d16ec3b9:/client#
```

Version of Google::ProtocolBuffers::Dynamic is 0.32.
Version of perl is 5.34.

**Comment by mbarbon** [comment]
Hi,
`protoc-gen-perl-gpd` is a `protoc` plugin, and is not supposed to be used directly.

You can see [protoc-gen-perl-gpd documentation](https://metacpan.org/dist/Google-ProtocolBuffers-Dynamic/view/scripts/protoc-gen-perl-gpd) for example usage.
