### ISSUE TITLE
Failed assertion in protoc-gen-perl-gpd

### ISSUE THREAD

**Issue by CyprusSocialite** [mbarbon/google-protobuf-dynamic#45]
```
> protoc --pertl-gpd_out=package=test test.proto

protoc-gen-pertl-gpd: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--pertl-gpd_out: protoc-gen-pertl-gpd: Plugin failed with status code 1.


> protoc-gen-perl-gpd --help

/usr/include/c++/8/bits/stl_vector.h:950: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) const [with _Tp = upb::Def*; _Alloc = std::allocator<upb::Def*>; std::vector<_Tp, _Alloc>::const_reference = upb::Def* const&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted
```

Happens with protobuf 3.11.0 and 3.19.1 - compiled from source.

**Comment by kfix** [comment]
@CyprusSocialite you mistakenly used `protoc --pertl-gpd_out` instead of `protoc --perl-gpd_out`

**Comment by jjatria** [comment]
Although the failure when running with `--help` is unseemly, the main issue seems here to be resolved.

FWIW, I cannot reproduce the failure locally (running with `--help` just hangs).

I suspect this issue can be closed.

**Comment by CyprusSocialite** [comment]
> @CyprusSocialite you mistakenly used `protoc --pertl-gpd_out` instead of `protoc --perl-gpd_out`

Apologies, I made a typo when reproducing the error for this issue. The actual error message is
`--perl-gpd_out: protoc-gen-perl-gpd: Plugin killed by signal 6.`

The `--help` issue is still happening to me, too

**Comment by mbarbon** [comment]
Hi, sorry for the delay. Could you provide the `test.proto` file that triggers he failure?
