### ISSUE TITLE
certain enum keynames should be forbidden from mapping

### ISSUE THREAD

**Issue by kfix** [mbarbon/google-protobuf-dynamic#46]
It's possible to map enum keys that are also keywords in the main:: package

```
$ cat PB_evil_enums.pm
package PB_evil_enums;

use strict;
use warnings;
use Google::ProtocolBuffers::Dynamic;

my $gpd = Google::ProtocolBuffers::Dynamic->new;
$gpd->load_string('', <<'EOD');
syntax = "proto2";
package evilenum_pb;

message console_log_line {
    // from: https://perldoc.perl.org/constant#CAVEATS
    enum perl_keywords {
        STDOUT = 1;
        STDERR = 2;
    }

    optional perl_keywords the_enum = 1;
}
EOD

$gpd->map(
   +{
      'package' => 'evilenum_pb',
      'prefix' => 'PB_evil_enums::_pb'
    },
);

print STDERR "STDERR is okay from module\n";

undef $gpd;
1;
```

loading this module causes misattributed errors when compiling subsequent scripts & modules:

```
$ perl -e 'print STDERR "hi"';
hi

$ perl -I. -MPB_evil_enums -e 'print STDERR "hi"';
STDERR is okay from module
String found where operator expected at -e line 1, near "STDERR "hi""
	(Do you need to predeclare STDERR?
```

this error is due to main::STDERR being converted from a fileglob to a constant sub:

```
$ perl -I. -MPB_evil_enums -e 'print STDERR()';
STDERR is okay from module
2
```

Perhaps `src/dynamic.cpp: Dynamic::map_enum()` should be dying on any enum field named with a [known perl keyword](https://perldoc.perl.org/constant#CAVEATS), or prefixing/suffixing those words with some special string to avoid the collision (but perhaps cause another?).

**Comment by mbarbon** [comment]
I used a different fix that should make it just work (at least in Perl 5.34, I will test older versions later)
