### ISSUE TITLE
Tests are failing in newer perls

### ISSUE THREAD

**Issue by jjatria** [mbarbon/google-protobuf-dynamic#48]
This seems to be related to the new boolean values introduces in 5.36.0 and the changes in how Data::Dumper stringifies these starting with 5.37.2. See https://github.com/DrHyde/perl-modules-Test-Differences/issues/21 for more context on this issue.

**Comment by mbarbon** [comment]
Thanks! I merged your fix. I will prepare a release as soon as I review some more pending issues.

**Comment by jjatria** [comment]
Excellent. Thanks taking a look!
